name: Build Documentation using Sphinx

on:
  pull_request:
  workflow_dispatch:
  
jobs:

  docsbuild:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-${{ hashFiles('**/make.bat') }}
        restore-keys: |
          {{ runner.os }}-pip-
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ".[Dev]"
    - name: Build with Sphinx
      run: |
        sphinx-build -E -b html --keep-going ./docsrc ./docs
