name: Build Documentation using Sphinx

on:
  pull_request:
  workflow_dispatch:
  
jobs:

  docsbuild:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-${{ hashFiles('**/make.bat') }}
        restore-keys: |
          {{ runner.os }}-pip-
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install furo
        python -m pip install sphinx-gallery
        python -m pip install sphinx-design
        python -m pip install --upgrade myst-parser
        python -m pip install sphinx_toolbox
        python -m pip install numpydoc
        python -m pip install .
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
    - name: Build with Sphinx
      run: |
        sphinx-build -E -b html ./docsrc
